name: Shipping service CICD 

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:
  
permissions: write-all

jobs:
  build_test_release:
    name: Build Test and Release
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@feature/deploy
    secrets: inherit

  deploy:
    needs: build_test_release
    name: Deploy
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/deploy.yml@feature/deploy
    secrets: inherit
